name: CI Pipeline - Sistema CA-SI 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Baixar o código (Checkout)
      uses: actions/checkout@v4
      
    - name: Instalar dependências e Rodar Testes (Auth)
      run: |
        cd auth-service
        npm install
        npm test  # Agora roda email + senha

    - name: Instalar dependências e Rodar Testes (Events)
      run: |
        cd events-service
        npm install
        npm test  # Roda validação de data

    - name: Montar o Docker Compose
      run: docker compose build

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Baixar o código
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  

    - name: Instalar dependências do Frontend
      run: |
        cd frontend-casi
        npm install

    - name: Tentar compilar o React (Build)
      run: |
        cd frontend-casi
        npm run build